source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'thin'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'jbuilder', '~> 1.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
# gem 'turbolinks'
# gem 'therubyracer', platforms: :ruby

group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'pry-rails'
  gem 'debugger'
  # gem 'better_errors'
  # gem 'binding_of_caller'
  # gem 'letter_opener'
  # gem 'mail_view'
  # gem 'quiet_assets'
  # gem 'sextant'
end
